### PR TITLE
Publish `package:web`

### PR DESCRIPTION
**Pull request by mosuem**
.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by kevmoo** [comment]
what's our story here, friends? We've made a few changes since this PR went out.

**Comment by mosuem** [comment]
> what's our story here, friends? We've made a few changes since this PR went out.

Forgot about this! Thanks for the ping.

**Comment by srujzs** [comment]
It took me a little while for some of the latest changes to roll into Flutter/google3 due to the monorepo, but that's done. A couple PRs opened up in the interim that I'm trying to land before publishing. Most of them have landed, but I'd ideally like to land https://github.com/dart-lang/web/pull/291 (just verifying some testing), update g3 (this should be trivial), and then publish sometime tomorrow/Wednesday. If it's really important we publish this ASAP, I can publish another minor release later.

**Review by srujzs — APPROVED** [review]
package:web is now up-to-date internally. Publishing SGTM!

**Comment by kevmoo** [comment]
@srujzs – I think it's cool for you to land

**Pull request merged**
