### PR TITLE
Fix the links in third_party/mdn/README.md

### PR DESCRIPTION
**Pull request by ksw2000**
I added hyperlinks for several missing links.

### CODE REVIEW

**Comment by kevmoo** [comment]
The links don't seem to work in the preview 🤷

**Comment by srujzs** [comment]
> The links don't seem to work in the preview 🤷

Is there a GitHub UI you're using to preview this? I tried it locally and it seemed to work.

**Review by srujzs — APPROVED** [review]
Thanks!

**Comment by kevmoo** [comment]
@srujzs – just the preview UI in the file UI

**Comment by srujzs** [comment]
Gotcha. It works for me using the same UI so not sure what's wrong here.

**Comment by kevmoo** [comment]
oh, maybe I'm holding it wrong. no worries. land it

**Pull request merged**
