### PR TITLE
Emit double as return value instead of num

### PR DESCRIPTION
**Pull request by srujzs**
Closes https://github.com/dart-lang/web/issues/57

In cases where the return type is known to be a double value, prefer double over num so users don't try and downcast the type, which won't work consistently on all compilers. In order to do this, _typeReference is amended to take an extra option 'returnType' which determines if the `_RawType` is used in a return type context.

### CODE REVIEW

**Comment by kevmoo** [comment]
Cool!

**Review by sigmundch — APPROVED** [review]
Nice!

**Comment by devoncarew** [comment]
FYI that when rolling this into google3 we ran into failures w/ some new diagnostics (unnecessary cast) in the devtools codebase. This has been addressed upstream in devtools, so `package:web` can roll in after the next devtools roll (cc @kenzieschmoll).

**Comment by kenzieschmoll** [comment]
CC @elliette who is on the DevTools release / roll rotation this month.

**Comment by elliette** [comment]
The DevTools roll into g3 was just submitted, so package:web should now be unblocked.

**Comment by devoncarew** [comment]
Thanks!

**Pull request merged**
