### PR TITLE
Move IDL version details

### PR DESCRIPTION
**Pull request by kevmoo**
etc to tool directory,Offers very little benefit for almost all users

### CODE REVIEW

**Comment by devoncarew** [comment]
It's true this may be providing too much info to users? I do think there's some value in letting them know that the package is generated from the IDL, and perhaps value in letting them know how current it is / how frequently it's updated? (i.e., `@webref/idl` / `3.43.1`).

(@srujzs is probably the best reviewer for this)

**Comment by srujzs** [comment]
I agree with Devon that it's useful to include this information in the main README. Having the direct source of truth immediately visible makes the generation seem less magical and makes it easy to find what has changed when we update the IDL version.

**Comment by kevmoo** [comment]
It's still SUPER easy to see the delta in the diff – local or on GitHub.

But it offers very little benefit to the user. And the link doesn't work on `pub.dev`, etc.

**Comment by srujzs** [comment]
It looks like they work here unless I'm missing some other context: https://pub.dev/packages/web.

If we do want to land this, maybe add a comment in the main readme to point to the readme in `tool/` e.g. `See tool/README.md for more details on what Web IDL version the tool uses and how to generate the bindings.`?

**Comment by kevmoo** [comment]
Not linked correctly here though; https://pub.dev/documentation/web/latest/

maybe that's just a bug

**Comment by srujzs** [comment]
I might be missing something again because those links still work for me. :D

**Comment by kevmoo** [comment]
PTAL

**Review by srujzs — APPROVED** [review]
Thanks!

**Pull request merged**
