### PR TITLE
Fix document.documentElement should return HtmlHtmlElement #214

### LINKED ISSUE #214: document.documentElement  should return HtmlHtmlElement
`document.documentElement` returns `Element?` but it should return [`HtmlHtmlElement?`](https://pub.dev/documentation/web/latest/web/HTMLHtmlElement-extension-type.html) according to [mdn's docs on HTMLHtmlElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHtmlElement)

> The HTMLHtmlElement interface serves as the root node for a given HTML document. This object inherits the properties and methods described in the [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) interface.

 > You can retrieve the HTMLHtmlElement object for a given document by reading the value of the [document.documentElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/documentElement) property.

### PR DESCRIPTION
**Pull request by ksw2000**
- Fix #214

### CODE REVIEW

**Comment by kevmoo** [comment]
These APIs are generated. We don't want to patch things in this way.

CC @srujzs

**Comment by ksw2000** [comment]
I think you're right; this issue seems a bit strange.

**Comment by jarrodcolburn** [comment]
You're saying

> The MDN notes also mention that it can be other types of `Element`s: https://developer.mozilla.org/en-US/docs/Web/API/Document/documentElement#notes.

at link^
> Document.documentElement returns the [Element]

...which it is an Element. But I'd say a `super` type, not an `other` type.

Especially since https://developer.mozilla.org/en-US/docs/Web/API/HTMLHtmlElement says 
> You can retrieve the HTMLHtmlElement object for a given document by reading the value of the [document.documentElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/documentElement) property.

**Comment by srujzs** [comment]
Sorry, I wasn't clear what I was referring to there. Specifically this sentence:

> For any non-empty XML document, documentElement will always be whatever element is the root element of the document.

This sentence leads me to believe this getter can return other types of `Element`s beyond just html elements, so if we made this `HTMLHtmlElement`, it might be wrong in some cases.

**Pull request closed without merging**
