### PR TITLE
Don't emit interface mixins

### PR DESCRIPTION
**Pull request by srujzs**
They should be added to the interfaces they are mixed into. This allows for external static members to use the right nominal type. This CL also adds some logic to handle name collisions between instance and static operations, which is now needed for exactly one pair of operations: Response.prototype.json and Response.json. Also enables asserts in the translator.

https://github.com/dart-lang/web/issues/56

### CODE REVIEW

**Review by sigmundch — APPROVED** [review]
Nice!

**Review by kevmoo — COMMENTED** [review]
Uh. Doesn't this mean, in some cases, you won't be able to polymorph over similar types since they won't share a base type?

**Comment by srujzs** [comment]
That's true, but that's intentional, since they're not supposed to be used as types.

https://webidl.spec.whatwg.org/#idl-interface-mixins

> Note that unlike [interfaces](https://webidl.spec.whatwg.org/#dfn-interface) or [dictionaries](https://webidl.spec.whatwg.org/#dfn-dictionary), [interface mixins](https://webidl.spec.whatwg.org/#interface-mixin) do not create types.

Do you have an example where they are that I overlooked? `GenericTransformStream` isn't used as a type in the IDL afaict. If they are used as types, then one option is to just move the `static` members to the mixing-in class and keep the instance members and mixin interface around.

**Comment by kevmoo** [comment]
> Do you have an example where they are that I overlooked?

I can imagine places where writing helpers/extensions on the shared types could be nice. I mean, we can always go back to these later. This is ABSOLUTELY a breaking change, though.

...I mean, if folks are actually using these types already. 🤷‍♂️

**Comment by srujzs** [comment]
Searching GitHub gave me no results for these mixin types being used with `package:web`, but that isn't too surprising. I've added this change to the changelog, and if we change our minds later about wanting these types to be emitted, we can go the route of [comment#5.](https://github.com/dart-lang/web/pull/90#issuecomment-1783204717).

**Pull request merged**
