### PR TITLE
Fix: deprecate local for rtcsession

### PR DESCRIPTION
**Pull request by jarrodcolburn**
see https://github.com/dart-lang/web/issues/178

### CODE REVIEW

**Comment by jarrodcolburn** [comment]
In https://github.com/dart-lang/web/issues/178 I suggest two recommendations. This is a PR that implements A, the first, to remove "local". 
This also includes a small test which refers to the MDN link mentioned.

**Comment by kevmoo** [comment]
Love it...BUT! These APIs are auto-generated. We'll need to figure out how to create exceptions or overrides or such

**Comment by jarrodcolburn** [comment]
Ah. It's not breaking my app, but it is causing me to have to do an unnecessary step in my code, hurting readability for anyone coming behind me. Working with RTC already hurts my brain

**Comment by jarrodcolburn** [comment]
Although, you're probably right "exceptions or overrides" will be needed at some point to tweak things. For this, I'm going to try to open a ticket on the actual definitions being used for auto generation, I guess that would be on the https://github.com/w3c/webref repo, right?

**Pull request closed without merging**
