### PR TITLE
rev to 0.4.1 in prep for publishing

### PR DESCRIPTION
**Pull request by devoncarew**
- rev to 0.4.1 in prep for publishing

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by devoncarew** [comment]
(we'll need to configure this package for github publishing - from pub.dev - before landing this PR)

**Review by srujzs — APPROVED** [review]

**Comment by srujzs** [comment]
> Let's talk about this! Flutter WILL NOT be able to roll to this because of pinning. What's the urgency here?

I'd assume users would just resolve to `0.4.0` because of the Flutter pin. Does this break anyone?

**Comment by devoncarew** [comment]
> Let's talk about this! Flutter WILL NOT be able to roll to this because of pinning. What's the urgency here?

Yeah, that's expected. It doesn't mean we shouldn't publish.

The issue with pinning comes up when you publish a new major version - that's not included in the `^x.y.z` range of most deps. See https://github.com/dart-lang/sdk/wiki/Flutter-Pinned-Packages for some background and details.

I would argue that we shouldn't even worry about publishing new major versions for this package however. It's still very early in its lifecycle, is a pre-1.0.0 package, and its more important to be able to evolve the API.

**Comment by devoncarew** [comment]
closing for now

**Pull request closed without merging**
